### PR TITLE
remove vcard-related pages and code

### PR DESCRIPTION
**Pull request by kareila**
I don't see any evidence that these are in use.  Correct me if I'm wrong...

### CODE REVIEW

**Comment by zorkian** [comment]
If there is one or two users, I'm still fine removing them.

**Comment by rahaeli** [comment]
I don't even remember what vcards are...

**Comment by azurelunatic** [comment]
Weren't they for ads? V stood for "vertical" if I recall correctly.

**Comment by kareila** [comment]
Heh, no. They are a standard XML-based format for communicating a set of contact information suitable for importing into a contact management program such as Outlook or Apple's Address Book.

**Pull request merged**
