### PR TITLE
More fixes for overlaying cgi-bin

### PR DESCRIPTION
**Pull request by anall**
Be aware that this is 90% automated, but tests still pass and Apache still starts.

### CODE REVIEW

**Comment by zorkian** [comment]
Apache starts -- can you ensure that at least you can log in, post entries, post comments, read the reading page, and log out?

**Comment by anall** [comment]
Also this is less important now that we've got the other PR merged, but gonna run through manual testing now

**Comment by anall** [comment]
( Doing this as a task list )

- [x] Log In
- [x] Post
- [x] Profile page (after fixing an unrelated bug)
- [ ] Comment -- Not validated, hold on
- [ ] Reading Page
- [ ] Log out

**Comment by zorkian** [comment]
Boom. Thanks for testing!

**Pull request merged**
