### PR TITLE
finish converting OpenID pages to TT

### PR DESCRIPTION
**Pull request by kareila**
I had these finished a few weeks ago but was waiting on the fabled #2660 merge to fix the one translation string that was referenced in talkpost_do.

Alas I couldn't actually test the workflow but I made sure the pages loaded without errors and looked OK. I didn't change any of the underlying logic except for where it was printing a blank page if you visited the URL directly instead of being redirected from elsewhere.

### CODE REVIEW

**Comment by zorkian** [comment]
This is the second time GitHub prompted me to resolve conflicts, so I did it, and then it says "can't be rebased due to conflicts" but I can no longer resolve them. WTF. Sorry, @kareila :((

**Comment by zorkian** [comment]
Other than that, LGTM, and that did_post not checking thing is weird but I buy it. Feel free to merge once GitHub agrees it's mergeable?

**Comment by kareila** [comment]
Okay will do!

**Comment by kareila** [comment]
It looks like I just had to drop the commit where I re-re-retidied that one file...

**Pull request merged**
