### PR TITLE
[#2166] Escape \@s instead of turning them into <user> tags

### PR DESCRIPTION
**Pull request by josh-berry**
This addresses issue #2166, by handling `\@` as an escape sequence.

I have **NOT** tested this in Dreamwidth's environment or in the actual DW codebase.  However, I wrote a little test program to validate the updated regex works as expected, as follows:

```perl
#!/usr/bin/perl

$DOMAIN = "default";

@tests = (
    ["\\.\@foo", 1],
    ["\\.\@foo.site", 1],
    ["\\\@foo", 0],
    ["\\\\\@foo", 1],
    ["\\\\\\\@foo", 0],
    ["whee \\\\\\\\\@foo bar", 1],
    ["\\\@foo.site", 0],
);

sub usertag {
    my ($user, $site) = ($_[0], $_[1] || $DOMAIN);
    return qq|<user name="$user" site="$site"/>|;
};

foreach my $tc (@tests) {
    my ($t, $res) = @$tc;
    print "$t => ";
    $t =~ s!(\\.)|(?<=[^\w/])\@([\w\d_-]+)(?:\.([\w\d\.]+))?(?=$|\W)!
            defined($1) ? "[$1]" : usertag($2, $3)
            !mge;

    print "$t\n";
    if ($res ^ $t =~ /</) {
        print "    FAILED\n";
    }
}
```

### CODE REVIEW

**Comment by josh-berry** [comment]
A signed CLA will be on its way shortly (via email).

**Comment by rahaeli** [comment]
And I have received said CLA: welcome, Josh!

**Comment by rahaeli** [comment]
(If nobody else has the chance in a few days to pull this branch and test that it does what it oughta do and doesn't do anything it shouldn't oughta do, btw, poke me and I will do it!)

**Comment by kaberett** [comment]
Oh awesome, welcome! :D (I am... going to bed not doing testing tonight.)

**Comment by zorkian** [comment]
Ergh, sorry for the slow merge here @josh-berry -- and thank you for providing the test script, that really helps with the confidence about the solution. Merged!

**Comment by josh-berry** [comment]
Not a problem, and thanks for merging!

**Pull request merged**
