### PR TITLE
Mood themes: Teeny Tinies variant

### PR DESCRIPTION
**Pull request by pinterface**
Seven new mood themes by phidari, color variants on the Teeny Tinies them to improve contrast against various backgrounds.

Files can be found here:

https://www.dropbox.com/sh/9fvnsjqnqzqd3d3/AADZc0299ITWerYS1Li_k96wa?dl=0

Olive, pink, yellow, brown, cyan, cherry, and grey.

### CODE REVIEW

**Comment by zarhooie** [comment]
omg TOO CUTE

On Thu, Apr 28, 2016 at 12:02 AM, Denise Paolucci <notifications@github.com>
wrote:

> Seven new mood themes by phidari, color variants on the Teeny Tinies them
> to improve contrast against various backgrounds.
>
> Files can be found here:
>
> https://www.dropbox.com/sh/9fvnsjqnqzqd3d3/AADZc0299ITWerYS1Li_k96wa?dl=0
>
> Olive, pink, yellow, brown, cyan, cherry, and grey.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dreamwidth/dw-free/issues/1759>
>



-- 
-Kat
Aut viam inveniam aut faciam.
I will either find a way or make one.

**Comment by pinterface** [comment]
Since the user who submitted the variants doesn't match the user of the
original theme, I wasn't quite sure how to name these.  For sorting 
purposes, it might make more sense to instead name them all "Chasy's
Teenie Tinies - Color" with credit to phidari in the description, except
the description doesn't actually seem to be shown anywhere.

**Comment by rahaeli** [comment]
Hm. "Chasy's Teenie Tinies - Blue by phidari"?

**Comment by pinterface** [comment]
Works for me!  Updated.

**Comment by kareila** [comment]
Bonus points for the helper script. 💯

**Comment by pinterface** [comment]
I was surprised there wasn't one already!  Inputting all those manually would be such a pain.

**Comment by kareila** [comment]
I was using copy/paste and search/replace. ✂️ 📋 😳

**Comment by rahaeli** [comment]
We don't tend to add mood themes often, so nobody's bothered automating it, so it's a pain, so we don't add mood themes often ...

**Pull request merged**
