### PR TITLE
adding .form.subject

### PR DESCRIPTION
**Pull request by azurelunatic**
getting rid of the extra colon on the mobile post page, now with more translation.

### CODE REVIEW

**Comment by kareila** [comment]
The only change I see in this commit is your changes to deadphrases.dat.  Can you also commit the other related changes to this branch?

**Comment by azurelunatic** [comment]
I can try. (I'm using the github web interface, which is kind of not the expected way.)

**Comment by rahaeli** [comment]
I will confess that I have occasionally deleted the branch and started over. BECAUSE GIT.

**Comment by kareila** [comment]
Okay, I committed the related changes from the other branch. I don't think adding this to deadphrases.dat is necessary.  Presumably the existing mobile page will DIAF at some point.

**Pull request closed without merging**
