### PR TITLE
Fix compounding blowout on new entry page [#2415]

### LINKED ISSUE #2415: Beta "create entry" page has outrageous compounding blowout on mobile
(`/entry/new`, not `/update`.)

You've probably already experienced this slapstick for yourself, but just in case:

user-blowout

The page starts ultra-hosed, and then every time you change the journal you're posting to it gets another 300+px wider. 

I have fixed this. Patch incoming. It's an ensemble comedy with multiple participants.

### PR DESCRIPTION
**Pull request by nfagerlund**
Resolves #2415.
Fixes one instance of #2421.

Last time, on etc. etc. etc.:

the blowout gif

Should be fixed:

**Mobile width:**

image

**Desktop width:**

image

**An in-between sorta thing:**

image

### CODE REVIEW

**Comment by nfagerlund** [comment]
Hey, by the way....... do we HAVE to manually babysit these vendor prefixes? Or is there an autoprefixer available somewhere in the SCSS build toolchain?

**Comment by nfagerlund** [comment]
Mmmmm I thought I had this one but some stuff about it is still bedeviling me. Consider this a draft for the next little bit.

**Comment by nfagerlund** [comment]
I think this one is also finally ready for review. Debugging those jquery components is certainly an adventure.

**Comment by nfagerlund** [comment]
After sleeping on it, I think it's better to not bend over backwards to preserve that weird +30px behavior. It looks perfectly good without it, and the component behaves much more predictably.

Once someone gives some feedback on this, I can rebase these commits so they make less of a mess.

**Comment by momijizukamori** [comment]
Yeah, I think we're okay ditching that 30px of padding if it's going to be messy to reimplement it - it's pretty minor aesthetics, and this is still technically in beta. This should be good to merge with a clean rebase!

**Comment by nfagerlund** [comment]
@momijizukamori Sweet! Rebased, and squashed it down to three commits so it reads a little more focused-like.

**Pull request merged**
