### PR TITLE
Use S2-based monthpage for style=site

### PR DESCRIPTION
**Pull request by afuna**
This exposes the work done in #693 by default, and removes the
talkread_s1short.bml file.

### CODE REVIEW

**Comment by anall** [comment]
Does this remove all uses of s1short -- I assume there's still some dead code for it hiding somewhere that hasn't been removed?

**Comment by afuna** [comment]
Not sure! I removed the ones that actually had an effect (in LJ::User) but I didn't comb through all the other if statements for dead code. 

Any chance you remember any specific areas to look at?

**Comment by anall** [comment]
I.... honestly have no idea.

I sort of lost track of this project, but if this is the last damn BML-handled "style=site" page, there has to be more code somewhere to rip out.

**Comment by afuna** [comment]
Thought I'd gotten it before, but have found just a bit more
(fixing in #1164)


On Tue, Jan 27, 2015, at 05:37 AM, Andrea Nall wrote:
> I.... honestly have no idea.


> I sort of lost track of this project, but if this is the last damn
> BML-handled "style=site" page, there has to be more code somewhere to
> rip out.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/pull/1160#issuecomment-71648325

**Pull request merged**
