### PR TITLE
(Bug 1046) Converts Popular FAQs Page to TT and Foundation

### PR DESCRIPTION
**Pull request by hotlevel4**
As per above. Downgrades the second title from h1 to h2.

Related to #1046.

### CODE REVIEW

**Comment by kareila** [comment]
We want to move away from having one controller per page, and group related controllers together into a single module.  So this should go in Support/Faq.pm instead of Faqpop.pm, like so:
```
DW::Routing->register_string( '/support/faq', \&faq_handler, app => 1 );
DW::Routing->register_string( '/support/faqpop', \&faqpop_handler, app => 1 );

sub faq_handler { ... }

sub faqpop_handler { ... }
```

**Comment by kareila** [comment]
Apart from that, this passes my eyeball test!  Once you get things reorganized I'll try to get it merged in.  Thanks!

**Comment by hotlevel4** [comment]
Added to Faq.pm. I'd planned on adding faqbrowse to Faq.pm, but I guess it makes sense to add faqpop there too.

**Comment by kareila** [comment]
Sorry for the delay getting back to this!  It looks good and tests fine, so I'll merge it in.  Thanks!

**Pull request merged**
