### PR TITLE
[#2432] Enable responsive comment thread indentation (opt-in)

### PR DESCRIPTION
**Pull request by nfagerlund**
(Previous rambling description moved to comments of #2432.)

This PR is now ready for review and merge as a "special preview" or "beta" or what have you. It does a couple of things: 

- **Adds some core2 features to enable responsive comment indentation.** See the commit message for full details, but basically this is a double opt-in: layouts have to enable it, and users have to turn it on after choosing a supported layout. 
- **Adds really basic responsive indent in Tabula Rasa and all descendents.** 
- **Adds a more advanced responsive indent in Practicality.**
- Adds some CSS convenience functions to core2, for making things invisible and doing mobile-only media queries. 
- Fixes or improves some unrelated mobile-frendliness stuff in Tabula Rasa and Practicality.

This screenshot is super long and I think basically un-previewable (and I think actually mobile browsers will refuse to load it at full resolution), but here's what the enhanced threading on Practicality looks like: 

[(click through for outrageously long screenshot)](https://user-images.githubusercontent.com/484309/59155217-50825b00-8a39-11e9-95e3-447d2a2a1998.png)

Once this is shipped, we should mention it in a broadcast-y venue and try to get peoples' feedback on it. Basically people will need to switch to a Practicality theme, go to their options page, and set "Indentation for nested comment threads" to "Responsive". They can also try it on any Tabula Rasa-based layout, but the results might be underwhelming. (They also might be underwhelming but still an improvement.)

### CODE REVIEW

**Comment by zorkian** [comment]
The dots are fairly easy to miss, at least in my scan, but maybe that's a coloring thing or such. There's just frankly not a lot of room to work with to try to convey the idea of horizontal movement, of course. If you have something that is better than what we have (which is nothing really) I'd be happy to commit it and ask the community for feedback.

I don't look at collapsed threads that much... oh god, I just tried, my journal is way worse than what you're showing here. At least you can see more than one word horizontally! Okay backing out of that now...

**Comment by nfagerlund** [comment]
@zorkian or whoever gets to merge this — can I request that this not be squashed into a single commit? Since this is a WIP feature, it'll be useful to preserve the ability to revert or pick through the individual parts of it. If you want me to squash the less relevant bits, I can do that.

**Comment by zorkian** [comment]
Sure, I can do it w/o squashing. I know there is still discussion happening on Discord, do you want me to hold off on this PR for now?

**Comment by nfagerlund** [comment]
@zorkian This is ready to go!

**Comment by zorkian** [comment]
From a code perspective, this looks correct and I don't see any issues, but I'm not the best equipped for best practices in this space. @momijizukamori do you want to take a look and see if you have any comments about the S2/CSS? If not, I'll just merge.

**Comment by zorkian** [comment]
Okay, going to land this but Momiji definitely feel free to comment & request updates!

**Pull request merged**
