### PR TITLE
Implement drafts and scheduled posts in the new update page

### PR DESCRIPTION
**Pull request by akpdw**
Fu, you wanted bugs 29 (draft posts) and 51 (scheduled posts) back, right?

This has drafts more or less working (probably needs some more testing without javascript, especially on
older browsers, plus some better error handling).  Scheduled posts also work, but only in the simplest way;
we don't even check for the dates being in the future, there's no notification for successful or unsuccessful
posts.  That probably needs the most work.

### CODE REVIEW

**Comment by zorkian** [comment]
So, @afuna, does this still need to be reviewed, or are there known changes that need to happen?

**Comment by afuna** [comment]
@zorkian yes and yes 

(or more specifically, the backend stuff needs another look, and the frontend stuff probably needs revamping to match new look / fix merge conflicts that have cropped up)

**Comment by zorkian** [comment]
Okay. Set label and unassigned. This is up for grabs for whomever wants to pull it forward.

**Comment by afuna** [comment]
Going to work on this, but I'd appreciate if you had a chance to look at the general approach involving cgi-bin/DW/BaseObj.pm, and I'll focus on the frontend in the meantime.

**Comment by zorkian** [comment]
(Form letter incoming.)

Last update was a while ago and there are outstanding requested changes -- we'd love to see this functionality, but it will probably need some TLC to get up to scratch. If someone does want to pick this back up we'd love to chat! In the meantime, I'm closing very old PRs to keep the board more clean.

**Comment by Sophira** [comment]
Do we at least have an open issue for this? As I understand it, this is the only thing keeping the new update page in beta and I'd hate for this to get forgotten.

**Comment by zorkian** [comment]
That's a great question. I don't know if there's an issue open. @afuna,
do you happen to know?

**Comment by kareila** [comment]
The open issue is #981 but it's just an empty stub pointing back here.

**Pull request closed without merging**
