### PR TITLE
Remove S1 memcache keys. Fixes #2255.

### LINKED ISSUE #2255: Get rid of remaining references to S1 memcache keys
The following S1 memcache keys are referred to in cgi-bin/LJ/User/Data.pm (wipe_major_memcache), htdocs/admin/memcache_view.bml, and or doc/raw/memcache-keys.txt, but not used anywhere else:

- s1overr
- s1uc
- s1pubstyc
- s1styc
- s1style
- s1style_all
- s1stylemap

Let's get rid of them there too.

### PR DESCRIPTION
**Pull request by pauamma**

### CODE REVIEW

**Comment by pauamma** [comment]
Tested as far as I could, which isn't a whole lot given that Dreamhacks don't have memcache installed.

**Comment by Sophira** [comment]
The Dreamhack machine does have `memcached` installed and usable, but it's not set up for Dreamhacks by default. I'd link to the wiki page on it, but the wiki seems to be down right now and I don't know the precise setup procedure myself.

I can give you a port number to use with it, though; I'll do that later today, so that when the wiki's back up, one of the steps is already done.

**Comment by alierak** [comment]
The wiki's fine, it's just http-only for some reason. I'm not sure if it ever supported https and can't log into Cloudflare to check.

**Comment by pauamma** [comment]
Will wait for port # assignment, then.

**Comment by pauamma** [comment]
OK, tested a bit more in depth. Seems to work.

**Comment by zorkian** [comment]
I'm impressed these lived this long. Nice axing!

**Pull request merged**
