### PR TITLE
Add encoding checks to comment importer

### PR DESCRIPTION
**Pull request by rshatch**

### CODE REVIEW

**Comment by alierak** [comment]
Are you sure this is the right / only section that would need modifying to handle other encodings? It looks to me like parser->parse appears several other places, including one that tries to special-case ISO-8859-1, and the place you've changed probably has to do with parsing the comment "meta" structure rather than the comment bodies.

**Comment by rshatch** [comment]
....I think you're right, looking at this, though I am too fried tonight to sort it out.

**Comment by zorkian** [comment]
This fails tidy, please tidy up and I'll merge!

**Comment by zorkian** [comment]
@rshatch any chance for that tidy? :D

**Comment by zorkian** [comment]
Tidied and merged.

**Comment by zorkian** [comment]
https://github.com/dreamwidth/dw-free/compare/5b84b6b4f0e0...43d44066d2b0

**Pull request closed without merging**
