### PR TITLE
Removing redundant colon from mobile post page

### PR DESCRIPTION
**Pull request by azurelunatic**
this has been getting up my nose for years

### CODE REVIEW

**Comment by kareila** [comment]
The proper ritual sacrifices need to be made for the translation system: you need to change the key to `.form.subject2` and so on. :bee: :bee:

**Comment by rahaeli** [comment]
Almost there! When you increment a string like that, you also need to change the reference in the file itself to invoke .form.subject2 instead of .form.subject.

**Comment by azurelunatic** [comment]
Whee! (oh god this is terrifying)

**Comment by rahaeli** [comment]
You're doing great! It's not your fault the translation system is an eldritch horror!

**Comment by azurelunatic** [comment]
Tonight's Storytime with Azz in -dev was explaining to @sgsabbage Why We Change The Code String Via Patch. It was all very baffling ("Because the steam-radiator still sits there angrily waiting for us to bark our shins on it in the middle of the night.") up until the moment he beheld the Translation UI, at which point he achieved enlightenment.

**Comment by azurelunatic** [comment]
(it's possible that I could *also* have removed the *other* colon from the file itself, but that would have been simple and easy. And also incorrect.)

**Comment by kareila** [comment]
I merged this manually so that I could squash down the commits. Thanks for fixing this!

**Pull request closed without merging**
