### PR TITLE
Fixes #2711

### LINKED ISSUE #2711: update Github user profile icon to HTTPS
It's encoded as `http://github.com/favicon.ico` which gets redirected to `https://github.com/favicon.ico`, but it's not getting upgraded, it's getting cached by the SSL proxy.

### PR DESCRIPTION
**Pull request by RMHolsen**
Fixes #2711

### CODE REVIEW

**Comment by kaberett** [comment]
*\o/* <3

**Comment by kareila** [comment]
Hooray!

Have you submitted your CLA yet? https://wiki.dreamwidth.net/wiki/index.php/CLA

**Comment by RMHolsen** [comment]
It should be in there! I sent it to D at the beginning of this month.

**Comment by zorkian** [comment]
@rahaeli ping?

**Pull request merged**
