### PR TITLE
convert /admin/invite pages to TT

### PR DESCRIPTION
**Pull request by kareila**
Part of the ongoing effort to remove BML pages from the site.

### CODE REVIEW

**Comment by zorkian** [comment]
We need a BML killing theme song. Another one bites the dust is probably too easy.

**Comment by rahaeli** [comment]
We Are The Champions?

**Comment by kareila** [comment]
IDK about BML conversion but this is the official code machete song: https://www.youtube.com/watch?v=-VaVKE82wMs

**Comment by rahaeli** [comment]
I think that works for BML conversion too!

**Pull request merged**
