### PR TITLE
Additional CSS class "tagnav" to provide customization options for tag

### PR DESCRIPTION
**Pull request by woggy**
Partial fix to #1126

### CODE REVIEW

**Comment by woggy** [comment]
And to address the Most Common Complaint:

.tagnav { display:none; } 
.tagnav-space { display:none; }

in the CSS will make the arrows Gone As Though They Never Were.

**Comment by azurelunatic** [comment]
<3

**Comment by afuna** [comment]
Hmmm. ponder ponder. For the space, how about we just do:

    """<a class="tagnav" href="$link.url">&rarr;</a> """;

(that is, have the space inside the print_tagnav_prev/next bits) so that it's easier to manipulate all around?

**Comment by woggy** [comment]
There was some discussion about whether folks wanted there to be spaces or not - figured we'd give them a separate handle so as to allow either option.

**Comment by afuna** [comment]
How about we do something like:

    <span class="tagnav"><a...></a> </span>

And that way there's only one class to target instead of having to look up two of them?

**Comment by woggy** [comment]
Some users requested the ability to remove the space between the arrows and
the tag name. if that's not a feature we want to support, then yes, I agree
that lumping everything under a single class is cleaner.

**Comment by afuna** [comment]
Gotcha. I suggest having just one class for now and then let's see how
much that changes people's experience of the tags!


On Tue, Jan 27, 2015, at 06:47 AM, woggy wrote:
> Some users requested the ability to remove the space between the
> arrows and
>
> the tag name. if that's not a feature we want to support, then
> yes, I agree
>
> that lumping everything under a single class is cleaner.
>
> On Jan 26, 2015 1:50 PM, "Afuna" <notifications@github.com> wrote:
>
>
> > How about we do something like:
>
> >
>
> > <span class="tagnav"><a...></a> </span>
>
> >
>
> > And that way there's only one class to target instead of having to
> > look up
>
> > two of them?
>
> >
>
> > —
>
> > Reply to this email directly or view it on GitHub
>
> > <https://github.com/dreamwidth/dw-free/pull/1153#issuecomment-71535420>.
>
> >
> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/pull/1153#issuecomment-71554980

**Comment by woggy** [comment]
done and tested. can smoosh the commits if need be, but I think it should be relatively clean as-is.

**Comment by afuna** [comment]
Great, thank you!

**Pull request merged**
