### PR TITLE
Bug2152 prime

### PR DESCRIPTION
**Pull request by annariel**
A rebased version of Bug2152.  Ready for (as yet unmade) changes requested from code review.

### CODE REVIEW

**Comment by zorkian** [comment]
Hiya! I'm going to place this up for grabs, but if you have any interest in getting back to it, please let us know!

**Comment by annariel** [comment]
No problem.  When I merged master into my development branch I bodged some of the conflict resolution and the resulting broken mess has been sitting on dream hack depressing me which means there's been no progress.

**Comment by afuna** [comment]
Sorry to hear that @annariel! It's almost there so I'll just finish this up :)

**Comment by zorkian** [comment]
Closing this, as it's been superseded by @afuna's last PR.

Thanks for writing on this @annariel! Yay! :D

**Pull request closed without merging**
