### PR TITLE
4504 twitter notifications of new posts

### PR DESCRIPTION
**Pull request by swaldman3**
Sorry that this took six months!
Updated following the review in https://github.com/dreamwidth/dw-free/pull/250.
Rebased on to develop of 31st August 2013 (because it was about a year behind!)
Expecting some more things to fix, but hopefully nothing major :-)

EDIT: there are a few comments in the old review that I didn't address. In those cases I've explained why in comments on the old PR. But if that's awkward to find, just raise the issues here and I'll explain!

### CODE REVIEW

**Comment by zorkian** [comment]
Updating labels. Would be great to see if we can get an owner for this and get it cleaned up and ready to go.

**Comment by me-and** [comment]
In case it's helpful to anyone, I've just rebased this code and dealt with the obvious merge conflicts at https://github.com/me-and/dw-free/commits/4504_twitter_postreview

**Comment by kaberett** [comment]
Wait there's an open bug for this? AWESOME.

https://dw-suggestions.dreamwidth.org/1327090.html

**Comment by kareila** [comment]
Thanks @me-and! I know I won't get around to looking at this for a bit longer yet, but that will make things much easier when I do.

**Comment by me-and** [comment]
@kaberett an open pull request rather than an open issue, so AIUI it'll want an issue raised before a fix can actually be merged…

**Comment by kareila** [comment]
The original issue was in Bugzilla, so I'm fine just referencing that unless further work is needed.

**Comment by zorkian** [comment]
(Form letter incoming.)

Last update was a while ago and there are outstanding requested changes -- we'd love to see this functionality, but it will probably need some TLC to get up to scratch. If someone does want to pick this back up we'd love to chat! In the meantime, I'm closing very old PRs to keep the board more clean.

**Pull request closed without merging**
