### PR TITLE
Remove unused code for browselang

### PR DESCRIPTION
**Pull request by kareila**
This gets rid of the `browselang` userprop and associated unused module `LJ/Setting/Language.pm`, as well as the site cookie for langpref.  We've never supported users choosing a persistent preference for a language different from the site's default language.

This is a larger set of changes than the other similar ones I've submitted recently, and the individual commit messages are informative.  I've lightly tested this by running the automated test suite, making sure "uselang=debug" still worked as expected, and testing sample event output using the /admin/eventoutput page.

### CODE REVIEW

**Comment by rahaeli** [comment]
WOOHOO CODE MACHETE

Just checking out of a sense of paranoia (since I can't see why it would), but does this break the ability for logged out people to set a site skin preference?

**Comment by kareila** [comment]
It shouldn't! There was a language cookie and a scheme cookie and I only removed the language one.

**Comment by rahaeli** [comment]
I figured! But better safe than sorry, etc.

**Comment by zorkian** [comment]
Thank you for the helpful commit messages.

**Pull request merged**
