### PR TITLE
Send offsite mood links through proxy.

### LINKED ISSUE #1342: Mood themes aren't https
They need to be run through the proxy I think! Because they break https on read pages ;)

### PR DESCRIPTION
**Pull request by anall**
Fixes #1342

[ This is untested except for the fact that the URL form looks correct.  I do not have the means or ability to test HTTPS proxying because there is no information on how the proxy end of things work ]

### CODE REVIEW

**Comment by afuna** [comment]
I suggest LJ::CleanHTML::https_url instead! That does a couple extra checks for if it's already https or if we're hosting it.

**Comment by anall** [comment]
That work?

[ again, untested besides the URL looking like it is getting mangled properly ]

**Comment by afuna** [comment]
Hmm it still seems to be using DW::Proxy::get_proxy_url.

**Comment by anall** [comment]
Try now?  I fail at git.

**Comment by afuna** [comment]
Looks good from an eyeball, let me see if I can confirm (but maybe not tonight!)

**Comment by rahaeli** [comment]
I sometimes think "I fail at git" is the default state. I know I do too. :)

**Comment by afuna** [comment]
Hmmm I think that this always converts to HTTPS, whether or not the page being viewed is in HTTP or HTTPS. But I think that given:

a) the url is cached
b) we plan to switch to https everywhere

That actually is a non-issue.

**Pull request merged**
