### PR TITLE
[#1649] add Markdown support to crossposted entries

### LINKED ISSUE #1649: Cross-posting Markdown doesn't work
I've just tried to cross-post from Dreamwidth to LiveJournal, where the original Dreamwidth post had `!markdown` in the first line and was correctly formatted as such. The LiveJournal post was cross-posted successfully, but with the raw formatting still in place (`*` around words that should be italics, double `<br>` around paragraphs, `!markdown` on the first line).

I'm using the beta Create Entries page, in case that makes any difference.

### PR DESCRIPTION
**Pull request by kareila**
Fixes #1649.

### CODE REVIEW

**Comment by zorkian** [comment]
This is definitely one of the hacks that will follow me forever

**Comment by rahaeli** [comment]
It's good to show new developers that we're not always perfect on the first try. ;)

**Comment by zorkian** [comment]
First try? I don't know what my excuse is... this is like the 9000th haha

**Comment by rahaeli** [comment]
shhhh you were supposed to take the polite face-saving excuse

**Comment by zorkian** [comment]
Whoop `>_>`

**Pull request merged**
