### PR TITLE
fixes for media file access

### PR DESCRIPTION
**Pull request by kareila**
Use a controller to do basic setup checking, including bouncing for a user domain cookie if needed - LJ::get_remote was failing when the user domain cookie wasn't available.

With that working, we can add functional support for viewall, and remove the FIXME comment that requested it.

Also, as @kaberett pointed out, crossposted entries that reference hosted images will fail to load on the remote site, so let's whitelist all known crosspost sites.

### CODE REVIEW

**Comment by zorkian** [comment]
Mmm. Interesting point about the crossposting. I hadn't considered that. I suppose if we wanted to get really fancy we could ensure it's on the exact page, but this is probably good enough? (I mean, it means you can use DW to host any image for posting on LJ? There's abuse potential but probably not enough to worry about.)

**Comment by alierak** [comment]
Well, exact page is kind of vague, it could be in that entry, on anybody's friends page.

**Comment by zorkian** [comment]
My dreams of nice, clean systems :(

**Comment by kareila** [comment]
If you wanted a nice, clean system, you shouldn't have based it on LJ 😆

**Comment by zorkian** [comment]
As they say .. #rekt :)

**Pull request merged**
